[env]
txPerPayload=250                               #nr of transactions per payloas
txIterations=1                                 #nr of iterations of payload deliveris... all txIterations * txPerPayload = all tx being sent
txMultiBroadCast = 1                           #nr of peers to multibroadcast to
txDescription="ARK-GO Testing program running" #txDescription
dbFileName = "db/testlog.db"

[account]
passphrase=""                                  #passphrase of the test tx sending account
secondPassphrase =""
recepient=""                                   #recepient of the transactions
