# Adapt and copy this file to settings/config.toml for productive configuration
# Do NOT change the headers in brackets, example: [delegate]
[delegate]
address = "ASJBHz4JfWVUGDyN61hMMnW1Y4ZCTBHL1K"
pubkey = "027acdf24b004a7b1e6be2adf746e3233ce034dbb7e83d4a900f367efc4abd0f21"

#DEVNET address settings (for testing on devnetwork)
Daddress = "DQUjMT6fhJWbwhaYL5pPdX9v5qPiRcAzRb "
Dpubkey = "02bcfa0951a92e7876db1fb71996a853b57f996972ed059a950d910f7d541706c9"

[voters]
shareRatio = 0.70 #percent goes to voters
txdescription = "delegate: voters share. Thank you! |tx by ark-go"
fidelity = true # reduce share of new voters
fidelityLimit = 24  #fidelity limit in hours - calculation: profit * (voted time / fidelityLimit)
minamount = 0.0 #minimum amount limit for payout.
minVoteTime = 0 #minimum vote time in hours to receive payout
deductTxFees = true #if true tx fees are deducted from recepients, if false fees are paid by reserver share
blocklist = "" #comma separated address list of addresses of voters to block
whitelist = "" #comma separated address list of addresses of voters to allow ( only applies to cap options)
capBalance = false #should the payout be capped?
balanceCapAmount = 0.0 #treshold to cap the balance
blockBalanceCap = true #Should the payout be completely blocked, false = pay profit for cap

[costs]
address = "ANqeL7CP2som7q9NFbRuaUc5WUnwYkSbFY" #costs
shareRatio = 0.15
txdescription = "delegate costs. |tx by ark-go" #not longer than 64 chars

#DEVNET address settings (for testing on devnetwork)
Daddress = "DMEvkeU7pNnH5eVDz63GVK6A4CThCmdcpk" #costs

[reserve]
address = "AKB7z6QLpCctVsj62nA7pBHk9zF6ocxZdJ" #reserve
shareRatio = 0.15
txdescription = "delegate reserve. |tx by ark-go" #not longer than 64 chars

#DEVNET address settings (for testing on devnetwork)
Daddress = "DQPr5WHkhau3Ka2RKb7egm7isr5wbNHbF1"

[personal]
address = "AKB7z6QLpCctVsj62nA7pBHk9zF6ocxZdJ" #reserve
shareRatio = 0.0
txdescription = "delegate personal. |tx by ark-go" #not longer than 64 chars

#DEVNET address settings (for testing on devnetwork)
Daddress = "DQPr5WHkhau3Ka2RKb7egm7isr5wbNHbF1"

[client]
network = "DEVNET" #which network is active when application starts
dbfilename = "payment.db"
statistics = true
statPeer = "164.8.251.91"
statPort = 54010
nodeversion = "1.0.1" #filter setting for node version list talk... only nodes with this version are used
#DEVNET nodeversion
Dnodeversion = "1.1.0" #filter setting for node version list talk... only nodes with this version are used
payloadsize = 30 #number of transaction sent to block in one payload
multibroadcast = 10 #to how many peers at once - we can multibroadcast

#ARK-POOL SERVER SETTINGS
[server]
port = 54000
address = "0.0.0.0"
dbfilename = "payment.db"

